# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn api.index:app --host 0.0.0.0 --port $PORT"
