# Nixpacks configuration for Railway deployment
# Backend Python/FastAPI apenas

[variables]
NIXPACKS_NO_MUSL = "1"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Backend Python build complete'"]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn api.index:app --host 0.0.0.0 --port $PORT"
