services:
  - type: web
    name: agente-eda
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "*"
      - key: DB_NAME
        value: agente_eda_db
      - key: GROQ_API_KEY
        sync: false  # Configure manualmente no dashboard
